fullnameOverride: creation-wizard-api

image:
  repository: ghcr.io/possible-x/catalog-shapes/sd-creation-wizard-api
  tag: latest
imagePullSecrets:
  - name: github-registry-auth
service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: cluster-issuer-letsencrypt
  className: "nginx"
  hosts:
    - host: sd-creation-wizard.dev.possible-x.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - sd-creation-wizard.dev.possible-x.de
      secretName: sd-creation-wizard-certificate
replicaCount: 1