#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

fullnameOverride: creation-wizard-api

image:
  repository: ghcr.io/possible-x/catalog-shapes/sd-creation-wizard-api
  tag: latest
imagePullSecrets:
  - name: github-registry-auth
service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: cluster-issuer-letsencrypt
  className: "nginx"
  hosts:
    - host: sd-creation-wizard.dev.possible-x.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - sd-creation-wizard.dev.possible-x.de
      secretName: sd-creation-wizard-certificate
replicaCount: 1